# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c06e6dc272458855b735a5761e437a43c1036828b9c3f1928be124247c88e7b6d8a7542b39450012900c514d6b93ad54d9154db55dd015997c70dd368d0189d

test:
  secret_key_base: e4861dca8df661b5942c955b750df70271a664053bcca1bc5d1546cec7ce3559066e71f65c3b1b6e96a6d08774a7f19e1a9a195d42458009d650b34aefa01888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
